### PR TITLE
Fix ctypes.util and ctypes.util.find_library issues on mac

### PR DESCRIPTION
**Pull request by VanL**
These changes allow scancode-toolkit-mini to work on m1/m2 macs with homebrew libmagic installed.

### CODE REVIEW

**Review by pombredanne — CHANGES_REQUESTED** [review]
Hey!
Thank you! Can I interest you in a DCO signoff?

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra if you have a minute, we would need to update the skeleton on this repo... it is rather outdated https://github.com/nexB/skeleton ... thank you in advance! :bow:

**Comment by AyanSinhaMahapatra** [comment]
> Thank you! Can I interest you in a DCO signoff?

@VanL thanks! Gentle ping!

**Comment by VanL** [comment]
This has been fixed upstream

**Comment by AyanSinhaMahapatra** [comment]
Thanks for the update @VanL

**Pull request closed without merging**
